<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RefundService.proto

namespace RefundService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RefundService.RefundResponse</code>
 */
class RefundResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string refundResponse = 1;</code>
     */
    protected $refundResponse = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $refundResponse
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RefundService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string refundResponse = 1;</code>
     * @return string
     */
    public function getRefundResponse()
    {
        return $this->refundResponse;
    }

    /**
     * Generated from protobuf field <code>string refundResponse = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRefundResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->refundResponse = $var;

        return $this;
    }

}

