<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RefundService.proto

namespace RefundService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RefundService.RefundRequest</code>
 */
class RefundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 userID = 2;</code>
     */
    protected $userID = 0;
    /**
     * Generated from protobuf field <code>int32 txid = 3;</code>
     */
    protected $txid = 0;
    /**
     * Generated from protobuf field <code>int32 orderID = 4;</code>
     */
    protected $orderID = 0;
    /**
     * Generated from protobuf field <code>string refundAddress = 5;</code>
     */
    protected $refundAddress = '';
    /**
     * Generated from protobuf field <code>string accessHash = 6;</code>
     */
    protected $accessHash = '';
    /**
     * Generated from protobuf field <code>int32 unixTime = 7;</code>
     */
    protected $unixTime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $userID
     *     @type int $txid
     *     @type int $orderID
     *     @type string $refundAddress
     *     @type string $accessHash
     *     @type int $unixTime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RefundService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 userID = 2;</code>
     * @return int
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     * Generated from protobuf field <code>int32 userID = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkInt32($var);
        $this->userID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 txid = 3;</code>
     * @return int
     */
    public function getTxid()
    {
        return $this->txid;
    }

    /**
     * Generated from protobuf field <code>int32 txid = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTxid($var)
    {
        GPBUtil::checkInt32($var);
        $this->txid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderID = 4;</code>
     * @return int
     */
    public function getOrderID()
    {
        return $this->orderID;
    }

    /**
     * Generated from protobuf field <code>int32 orderID = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderID($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string refundAddress = 5;</code>
     * @return string
     */
    public function getRefundAddress()
    {
        return $this->refundAddress;
    }

    /**
     * Generated from protobuf field <code>string refundAddress = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRefundAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->refundAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string accessHash = 6;</code>
     * @return string
     */
    public function getAccessHash()
    {
        return $this->accessHash;
    }

    /**
     * Generated from protobuf field <code>string accessHash = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unixTime = 7;</code>
     * @return int
     */
    public function getUnixTime()
    {
        return $this->unixTime;
    }

    /**
     * Generated from protobuf field <code>int32 unixTime = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setUnixTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->unixTime = $var;

        return $this;
    }

}

